### ISSUE TITLE
Plugins fail to load with Reaper on Windows XP Pro 32-bit Service Pack 3

### ISSUE THREAD

**Issue by andrewreeman** [andrewreeman/SpectralSuite#19]

**Comment by andrewreeman** [comment]
[](url)

**Comment by andrewreeman** [comment]
There are two parts to this issue.

1. To succesfully load the vsts in the plugin list we must tick 'Do not scan VST names/types' in the vst config menu on Reaper. 

2. Once this is done Reaper states that the plugin cannot be loaded when selected from the list.

**Comment by endphp2** [comment]
VST3 versions or DLL files?

**Comment by andrewreeman** [comment]
These are for the unreleased 32 bit .dll versions and vst3 versions. The next plugin release will contain 64 bit .dll, vst3 and AU and 32 bit versions.

**Comment by andrewreeman** [comment]
The JUCE framework does not support windows XP. Trying the basic example from the JUCE framework also did not work. Closing the issue as this cannot be fixed.
