### ISSUE TITLE
SpectralSuite 2.0.3 - AU doesn't work

### ISSUE THREAD

**Issue by bbbmusic** [andrewreeman/SpectralSuite#24]
The AU-versions (2.0.3) didn't work, except Spectral Gate. Content is missing. 
Have a look at the screenshots. No 1 is from logics plugin manager. No 2 from apple finder. No 3 from apple finder viewing package content.
![screenshot-spectralsuite](https://user-images.githubusercontent.com/41027137/61588318-e9100d00-ab99-11e9-9c21-0541c5547965.png)

**Comment by andrewreeman** [comment]
Nice find! Just raised an issue related to this: #25 .  The [zip](http://andrewreeman.github.io/media/SpectralSuite-latest.zip) files have now been updated to include the complete components.
