### ISSUE TITLE
Save state issue with Morph 

### ISSUE THREAD

**Issue by StanleyThat** [andrewreeman/SpectralSuite#26]
![image](https://user-images.githubusercontent.com/73564460/137231950-3fb60a66-1d3f-41bd-89ee-0d7e5eaf1c0d.png)
Hey there
I'm using Morph version 2.1.3, within FL Studio 20, unfortunately, whenever I save my project, I get this save state error. I also have Spectral Gate loaded in the project but it does not have this issue. Also, I am able to save presets within FL studio and there is no problem loading them, but when I go to save the entire project I get the save state error in the first pic.
![image](https://user-images.githubusercontent.com/73564460/137232188-c59cd9ca-dad9-4e4d-9b72-295dd1e3adeb.png)

**Comment by andrewreeman** [comment]
I've not actively investigated this but the newer versions of Morph slightly changed the way saving works. Possibly that it might be fixed 🤞

**Comment by andrewreeman** [comment]
Can you confirm if the latest versions fixes this issue?

**Comment by andrewreeman** [comment]
I can't fully test this as the trial version of FL studio does not load projects but it does apparently allow saving.
I managed to save a project successfully with the latest versions.

However, another caveat of the trial version is that I can't save presets so I can't test that on FL Studio either
