### ISSUE TITLE
Script for generating a new plugin

### ISSUE THREAD

**Issue by andrewreeman** [andrewreeman/SpectralSuite#40]

**Comment by pixmusix** [comment]
Hi @andrewreeman.
I can see that alot of the issues for this repo are exiting new ideas for effects to be added to the suite.
A scrtipt seems like the right place to start.
Is this something I can assist you with?

**Comment by andrewreeman** [comment]
It is a bit annoying to create a new plugin at the moment. I usually copy and existing plugin and change everything...and the larger the plugins get the more troublesome that is! 

There are 2 plugins that are "development" tools. The :"Playground" one and the jucer project in `SpectralSuiteBuild`. 
The `SpectralSuiteBuild` one may be a good use as a template for a new plugin.

If you were willing to help out with this part that would be great, it would make it easier for other people to create new plugins too.

I'd probably say if you can get the `Base.jucer` project building, and then create a script that will copy that to a new folder and rename all instances of `Base...` to the new plugin name...if you're lucky that will be all there is to do! 

Any well known language for the script is probably fine, in this project I'm using ruby for mac and powershell for windows. Python may have been a better choice but I wanted to up my ruby and pwsh game! But use whatever you want for this.

Feel free to split this issue into smaller ones too if that helps.

Let me know your thoughts :-)

**Comment by pixmusix** [comment]
### To inherit or fake it?

>The SpectralSuiteBuild one may be a good use as a template for a new plugin.

I want to clarify here. *Are you suggesting we convert [this file](https://github.com/andrewreeman/SpectralSuite/blob/95a7f81fa94128cb668ca1fc0c41e5df7b800af8/SpectralSuiteBuild/BaseProcessor.h) into a c++ template<> and then inherit when making a new plugin?* I believe in cpp template arguments are resolved at compile time so it may make it hard keep variables flexible (e.g. fft bin size). Not a deal breaker; do you have any thoughts on inheritance in this repository?

>Base.jucer project building, and then create a script that will copy that to a new folder and rename all instances of Base... to the new plugin name...if you're lucky that will be all there is to do!

This feels a lot more pragmatic.
Python is a well known language which will be good for further contribution. 
However I think keeping the number of languages a contributor needs to know low is good for repository health.
*What's your preference here?*

*Have you started work on this? Is there some existing ruby I should look at or am I starting from scratch?* :)

### Clean before improvements?

I haven't read through all the github issues on this repo. **Should we look into resolving some of the bugs in the code before looking into adding more plugins?**

**Comment by andrewreeman** [comment]
Apologies it's taken so long to respond. This is still a valuable issue to tackle at some point.
When I say 'template' here I'm not actually referring to a C++ template, I mean more as a 'template' file we can just replace placeholders in to actual plugin names etc.
For generating a new plugin I was thinking that a new plugin script would just copy the Base.jucer file and the related source files to a new plugin folder and renamed classes to be the new plugin name. So it wouldn't require c++ templates or inheritance etc.

For the language, Python would be a good choice for this and make it easier for people to contribute. I don't see much problem introducing that to the repository really. 

I think this particular issue could be worked on independently from bug fixing. I'm prioritising bug fixing over other things that I work on, mainly related to the Morph plugin which is...a fun plugin but quite unstable!

I appreciate it's taken a while for me to respond so if you're no longer interested or have the time to contribute to this repository that's fine, these conversations are always useful notes for other contributors also.

Thanks again for the willingness to help 👍

**Comment by pixmusix** [comment]
Hi @andrewreeman.

> Apologies it's taken so long to respond.

Totally understand; modern life is... pretty big. 😄 

> For the language, Python would be a good choice

Sounds good.

> I think this particular issue could be worked on independently from bug fixing

I'm cool with that.
If you're happy to sort out the bugs I'm happy to tackle this problem.
Are you using [producer](https://docs.juce.com/master/tutorial_manage_projucer_project.html) to create new projects?

**Comment by andrewreeman** [comment]
Sounds good. 
Yea producer is currently used to generate the visual studio / XCode projects. So really, the only thing that needs to be automatically copied for a new project is that .jucer file and the .cpp and .h files in 'SpectralSuiteBuild'. 

Feel free to push an early work-in-progress branch of this or open a draft PR to check we're both thinking of similar things 👍 

Appreciate your help with this, thank you so much

**Comment by pixmusix** [comment]
>Appreciate your help with this, thank you so much

Pleasure. :)

#### I think I'd like to tackle this as follows.
**First**, on this thread I'll post some basic python code to make sure where on the same page and I'm actually copy the correct files.

**Second**, It would then be really useful to have an example to play with.
i.e. I think you should create a new branch off main and in that new branch create a project from producer and all the other steps you would want to take before running my script.

Then I'll fork that branch instead of main. 
I know it's a little extra work for you, but the benefit is that I'll be able to test and find silly bugs instead of just opening 100 PRs. 
If you can teach me your processes for building your plug-ins, I'll be able to be a lot more helpful concerning this script and going forward. 🎧 

What do you think?

**Comment by andrewreeman** [comment]
Yea that sounds like a good method. We can do both at once too. So I'll create a new plugin from that base project on new branch and you can see what's changed. Hopefully not much!

**Comment by andrewreeman** [comment]
Here's a branch and draft PR as an example of creating a new plugin: https://github.com/andrewreeman/SpectralSuite/pull/46

Hopefully that helps. You can see through the commit history as well each stage

We can discuss any details of it on there but as you can see it's mainly renaming files and references etc. Bear in mind the plugin name containing spaces + a description in the projucer project. 

Let's leave off adding a description for the plugin actually for a script that creates one. Instead we can just remove the default description

**Comment by pixmusix** [comment]
> Hopefully that helps

Makes my job super clear. Nice! 👍 

------------------------

> You can see through the commit history as well each stage

That's clever! 👏 

-----------------------

> Bear in mind the plugin name containing spaces + a description in the projucer project.
Let's leave off adding a description for the plugin actually for a script that creates one. Instead we can just remove the default description

I'm not sure I understand this part. *Are you talking about the plug-in name that would come up in the DAW user interface?*

-----------------------

> it's mainly renaming files and references etc

I'll get to work. 
Since you've made that new branch I''ll just fork the branch and keep you updated here as I have questions.

**Comment by andrewreeman** [comment]
Great thank you! 

And yea I'm talking about the plugin name that appears in the DAW. It's set in the projucer file. I'll comment on that Pr about it

**Comment by andrewreeman** [comment]
@pixmusix Thanks to your change this can now be closed. Thanks again for the work on this
