### ISSUE TITLE
In Spectral Gate, the checkmark of "Enable tilt" disappears after closing and reopening the UI

### ISSUE THREAD

**Issue by Jerry1143** [andrewreeman/SpectralSuite#49]
I tried to click on the "Enable tilt" button on the UI of Spectral Gate, and then at first it showed the checkmark and sounded reasonable when adjusting the Gate tilt. However, the checkmark of "Enable tilt" disappears after closing and reopening the UI. It is not a serious problem in my opinion since it actually still sounded right. But I appreciate if this problem can be solved, because it can be confusing sometimes. Thank you for developing these useful plugins by the way :)

**Comment by andrewreeman** [comment]
That's certainly some strange behaviour. When I get a chance I'll take a look at it. Thanks for reporting this. Much appreciated

**Comment by andrewreeman** [comment]
It looks like the pull request kindly submitted by @a5632645 will fix this issue. So the next version should have this in 👍
