### ISSUE TITLE
Crashed Validation on M1 Mac Logic X

### ISSUE THREAD

**Issue by nishant2397** [andrewreeman/SpectralSuite#61]
Everything except Frequency Shifter and Morph crashed validation. I'm on an M1 Mac system, Logic X, Rosetta enabled.

**Comment by andrewreeman** [comment]
Thanks for the report, this is something that will be fixed in version 2.1.11. Once that's released you can try it out and let me know if it works 🤞

**Comment by andrewreeman** [comment]
This new version works for me, tested with Intel Mac with Logic X.

https://github.com/andrewreeman/SpectralSuite/releases/tag/v2.1.11

Let me know the results of this one 🤞

**Comment by nishant2397** [comment]
this version works great, thank you for your work. this is an amazing set of plugins!

**Comment by andrewreeman** [comment]
Glad it worked 👍 Enjoy making music
